.catalog:
  version: "1.0"
  minimum_rancher_version: 1.1.4
  questions:
  - variable: SCALE
    description: >
      Number of git mirror instances to schedule.
    label: Mirror Scale
    type: int
    default: 3
  - variable: ETCD_ENDPOINTS
    description: >
      The Etcd service used for coordinating updates, in service.stack format.
      An invalid or no service will fallback to poll-only mirroring.
    label: Etcd Service
    type: string
    default: http://etcd.etcd-ha:2379
  - variable: POLL_PERIOD
    description: >
      Poll each Git repository for changes after a configurable period of time.
    label: Polling Period
    type: string
    default: 5m
  - variable: REPO
    description: Comma-delimited list of Git repositories to mirror.
    label: Mirrored Repos
    type: string
    default: >
      https://github.com/rancher/rancher-catalog,
      https://github.com/rancher/community-catalog,
      https://github.com/rancher/infra-catalog
  - variable: DEBUG
    description: Enable debug-level logging.
    label: Debug Logging
    type: boolean
    default: false
  - variable: HOST_LOG_PATH
    description: Host path to bind mount nginx log directory to
    label: Host Log Path
    type: string
    default: /efs
mirror:
  scale: ${SCALE}
  health_check:
    request_line: GET / HTTP/1.0
    port: 80
    interval: 5000
    response_timeout: 3000
    healthy_threshold: 2
    unhealthy_threshold: 2
