.catalog:
  version: "1.0"
  minimum_rancher_version: 1.1.4
  questions:
  - variable: SCALE
    description: Number of git mirror instances to schedule. Ignored if global is set to 'true'.
    label: Mirror Scale
    type: int
    default: 3
  - variable: ETCD_SERVICE
    description: The Etcd service used for coordinating updates. Invalid or no coordination service will result in poll-only mirroring.
    label: Etcd Service
    type: service
    default: etcd
  - variable: SERVE_PORT
    description: Port to serve traffic on
    label: Port
    type: int
    default: 80
  - variable: HOST_LOG_PATH
    description: Host path to bind mount nginx log directory to
    label: Host Log Path
    type: string
    default: /efs
  - variable: ANALYSIS_PERIOD
    description: Do not consider log entries older than this period of time
    label: Analysis Period
    type: string
    default: 24h
mirror:
  scale: ${SCALE}
  health_check:
    request_line: GET / HTTP/1.0
    port: 80
    interval: 5000
    response_timeout: 3000
    healthy_threshold: 2
    unhealthy_threshold: 2
